version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"

  flask:
    build: .
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/test_student_db